name: Perl Dependency Submission
on:
  push:
    branches:
      - main

# 依存関係をサブミットするために、APIにはリポジトリへの書き込み権限が必要
permissions:
  contents: write

jobs:
  perl-action-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - run: cpanm Carmel --notest

      - name: Setup dependencies
        run: carmel install && carmel rollout

      - name: Generate data
        run: carmel list | carmel exec -- perl scripts/parse-carmel-list.pl > data.json

      - name: Submit
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/benevolent0505/perl-cpan-dep-test/dependency-graph/snapshots \
            -d @data.json

      - name: delete data
        run: rm data.json

